import {
  logContentError,
  logContentWarning,
} from '@ferolyte/common/content/diagnostics/content-diagnostic';
import { isVersionAtLeast } from '@ferolyte/common/content/versions/compare-version';
import {
  LANG_KEYS,
  LocalizedString,
  isValidLocalizedString,
} from '@ferolyte/common/content/localization/localized-string';
import type { ComponentOverride } from '../generated/runtime';

/** SDK sugar of block components; everything else is generated from the schemas. */
export const blockOverrides: Record<string, ComponentOverride> = {
  /**
   * `tags: ['a', 'b']`: from format 1.26.20 on the component `minecraft:tags: ['a', 'b']`, before that the legacy
   * keys `tag:a: {}`, `tag:b: {}` (the format version is the one written to the file).
   */
  tags: {
    build: (config, ctx) => {
      if (!Array.isArray(config) || config.length === 0) {
        logContentError(ctx, 'Block tags must be a non-empty array');

        return undefined;
      }
      for (let index = 0; index < config.length; index++) {
        const tag = config[index];
        if (typeof tag !== 'string' || tag.length === 0) {
          logContentError(
            ctx !== undefined ? { ...ctx, fieldPath: `[${index}]` } : undefined,
            'Block tags must be non-empty strings',
          );

          return undefined;
        }
      }
      if (
        ctx?.outputVersion !== undefined &&
        isVersionAtLeast(ctx.outputVersion, '1.26.20')
      ) {
        return { 'minecraft:tags': [...config] };
      }

      return Object.fromEntries(config.map((tag: string) => [`tag:${tag}`, {}]));
    },
  },
  /**
   * `strongly_powered_face` is one face (the game rejects a list since 1.26.50). A one-element list of older
   * configs is unwrapped with a warning; a longer list is an error.
   */
  redstoneProducer: {
    pre: (config, ctx) => {
      const face = config?.stronglyPoweredFace;
      if (!Array.isArray(face)) {
        return config;
      }
      const at = ctx !== undefined ? { ...ctx, fieldPath: 'stronglyPoweredFace' } : undefined;
      if (face.length > 1) {
        logContentError(
          at,
          `stronglyPoweredFace takes one face, got ${face.length} (${face.join(', ')}); Minecraft rejects a list`,
        );

        return { ...config, stronglyPoweredFace: face[0] };
      }
      if (face.length === 0) {
        logContentWarning(at, 'stronglyPoweredFace is an empty list; not written');
        const { stronglyPoweredFace: _list, ...rest } = config;

        return rest;
      }
      logContentWarning(
        at,
        `stronglyPoweredFace is one face, not a list; written as "${String(face[0])}"`,
      );

      return { ...config, stronglyPoweredFace: face[0] };
    },
  },
  /** With a known identifier the value is the language key generated by the compiler. */
  displayName: {
    pre: (config: LocalizedString, ctx) => {
      if (!isValidLocalizedString(config)) {
        logContentError(ctx, 'Display name must be a non-empty string');

        return undefined;
      }

      return ctx?.identifier !== undefined
        ? LANG_KEYS.block(ctx.identifier)
        : typeof config === 'string'
          ? config
          : Object.values(config)[0];
    },
  },
};
