import {
  logContentError,
} from '@ferolyte/common/content/diagnostics/content-diagnostic';
import {
  LANG_KEYS,
  LocalizedString,
  isValidLocalizedString,
} from '@ferolyte/common/content/localization/localized-string';
import type { ComponentOverride } from '../generated/runtime';

/** SDK sugar of block components; everything else is generated from the schemas. */
export const blockOverrides: Record<string, ComponentOverride> = {
  /** `tags: ['a', 'b']` is written as `tag:a: {}`, `tag:b: {}`. */
  tags: {
    build: (config, ctx) => {
      if (!Array.isArray(config) || config.length === 0) {
        logContentError(ctx, 'Block tags must be a non-empty array');

        return undefined;
      }
      const result: Record<string, object> = {};
      for (let index = 0; index < config.length; index++) {
        const tag = config[index];
        if (typeof tag !== 'string' || tag.length === 0) {
          logContentError(
            ctx !== undefined ? { ...ctx, fieldPath: `[${index}]` } : undefined,
            'Block tags must be non-empty strings',
          );

          return undefined;
        }
        result[`tag:${tag}`] = {};
      }

      return result;
    },
  },
  /** With a known identifier the value is the language key generated by the compiler. */
  displayName: {
    pre: (config: LocalizedString, ctx) => {
      if (!isValidLocalizedString(config)) {
        logContentError(ctx, 'Display name must be a non-empty string');

        return undefined;
      }

      return ctx?.identifier !== undefined
        ? LANG_KEYS.block(ctx.identifier)
        : typeof config === 'string'
          ? config
          : Object.values(config)[0];
    },
  },
};
