// Runs the schema conformance tests, then writes:
//   docs/roadmap/schema-report.md                          (errors + strictness diff)
//   packages/pack/tests/schema/known-failures.json         (baseline for it.fails)
import { execSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { ROOT, loadComponents, snake } from './ts-types.mjs';

const SCHEMAS = path.join(ROOT, '.cache/bedrock-schemas');
const RESULTS = path.join(ROOT, '.cache/schema-results.json');
const REPORT = path.join(ROOT, 'docs/roadmap/schema-report.md');
const BASELINE = path.join(ROOT, 'packages/pack/tests/schema/known-failures.json');

if (!existsSync(SCHEMAS)) {
  console.error('Schemas missing: run `node scripts/schemas/fetch.mjs` first');
  process.exit(1);
}

try {
  execSync('npx vitest run packages/pack/tests/schema', {
    cwd: ROOT,
    stdio: 'ignore',
    env: { ...process.env, SCHEMA_RESULTS: RESULTS },
  });
} catch {
  // failures are expected, results are still dumped
}
const results = JSON.parse(readFileSync(RESULTS, 'utf8'));
const tsInfo = new Map(loadComponents().map((c) => [`${c.kind}/${c.key}`, c]));

// ---- schema definition lookup ----
const load = (f) => JSON.parse(readFileSync(path.join(SCHEMAS, f), 'utf8'));
const schemas = {
  entity: { doc: load('behavior/entities/entities.json'), root: 'minecraft:entity' },
  item: { doc: load('behavior/items/items.json'), root: 'minecraft:item' },
  block: { doc: load('behavior/blocks/blocks.json'), root: 'minecraft:block' },
};

const resolve = (doc, node, depth = 0) => {
  while (node && node.$ref && depth++ < 20) {
    node = node.$ref.replace('#/', '').split('/').reduce((n, k) => n?.[k], doc);
  }

  return node;
};

function schemaComponent(kind, outKey) {
  const { doc, root } = schemas[kind];
  const rootDef = resolve(doc, doc.properties[root]);
  const comps = resolve(doc, rootDef?.properties?.components);
  const def = resolve(doc, comps?.properties?.[outKey]);
  if (!def) return undefined;
  const required = new Set(def.required ?? []);
  for (const branch of [...(def.allOf ?? []), ...(def.anyOf ?? []), ...(def.oneOf ?? [])]) {
    for (const r of resolve(doc, branch)?.required ?? []) required.add(r);
  }

  return { required };
}

// ---- build report ----
const baseline = {};
const lines = [];
const diffs = [];
let failing = 0;

for (const r of results.sort((a, b) => `${a.kind}/${a.component}`.localeCompare(`${b.kind}/${b.component}`))) {
  const bad = r.buildError !== undefined || r.errors.length > 0;
  if (bad) {
    failing++;
    (baseline[r.kind] ??= []).push(r.component);
    lines.push(`### ${r.kind} / \`${r.component}\``);
    if (r.buildError) lines.push(`- build: ${r.buildError}`);
    const shown = r.errors.slice(0, 8);
    for (const e of shown) lines.push(`- \`${e.path || '/'}\` ${e.message}`);
    if (r.errors.length > shown.length) lines.push(`- … ${r.errors.length - shown.length} more`);
    lines.push('');
  }

  const info = tsInfo.get(`${r.kind}/${r.component}`);
  const kind = r.kind === 'entity_behavior' ? 'entity' : r.kind;
  if (!info) continue;
  const outKey = r.outputKeys[0];
  const def = outKey && schemaComponent(kind, outKey);
  if (!def) {
    if (outKey) diffs.push(`| ${r.kind} | \`${r.component}\` | \`${outKey}\` | _no schema definition_ | |`);
    continue;
  }
  const ts = new Set(info.required.map(snake));
  const tsOnly = [...ts].filter((f) => !def.required.has(f));
  const schemaOnly = [...def.required].filter((f) => !ts.has(f));
  if (tsOnly.length || schemaOnly.length) {
    diffs.push(
      `| ${r.kind} | \`${r.component}\` | \`${outKey}\` | ${tsOnly.map((f) => `\`${f}\``).join(', ')} | ${schemaOnly.map((f) => `\`${f}\``).join(', ')} |`,
    );
  }
}

const md = [
  '# Schema conformance report',
  '',
  `Generated by \`npm run schemas\` against Blockception/Minecraft-bedrock-json-schemas. Do not edit.`,
  '',
  `Fixtures: ${results.length}, failing: ${failing}. The failing list is the T09 backlog (\`known-failures.json\`).`,
  '',
  '## Validation errors',
  '',
  ...(lines.length ? lines : ['None.', '']),
  '## Strictness diff (top-level fields)',
  '',
  'TS-required = non-optional in the SDK interface but optional in the schema; schema-required = the reverse.',
  '',
  '| Kind | SDK key | Output key | TS-required only | Schema-required only |',
  '|---|---|---|---|---|',
  ...diffs,
  '',
].join('\n');

mkdirSync(path.dirname(REPORT), { recursive: true });
writeFileSync(REPORT, md);
writeFileSync(BASELINE, `${JSON.stringify(baseline, null, 2)}\n`);
console.log(`report: ${path.relative(ROOT, REPORT)} (${failing}/${results.length} failing)`);
