// Round-trip conformance (schema ⊆ SDK): runs the vitest harness, then writes
//   docs/roadmap/roundtrip-report.md / .json   (summary + failing paths with a repro each)
//   packages/pack/tests/roundtrip/known-gaps.json   (only with --update-gaps)
// The harness imports the TypeScript sources (never dist/) through vitest.
import { execSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const RESULTS = path.join(ROOT, '.cache/roundtrip-results.json');
const REPORT = path.join(ROOT, 'docs/roadmap/roundtrip-report.md');
const REPORT_JSON = path.join(ROOT, 'docs/roadmap/roundtrip-report.json');
const GAPS = path.join(ROOT, 'packages/pack/tests/roundtrip/known-gaps.json');
const CATEGORIES = ['REJECTED', 'TYPE', 'LOST_FIELD', 'CHANGED', 'UNKNOWN_COMPONENT'];
const AREAS = ['entity', 'entity_behavior', 'item', 'block'];

if (!existsSync(path.join(ROOT, '.cache/bedrock-samples'))) {
  execSync('node scripts/schemas/fetch-samples.mjs', { cwd: ROOT, stdio: 'inherit' });
}
if (!existsSync(path.join(ROOT, '.cache/bedrock-schemas'))) {
  execSync('node scripts/schemas/fetch.mjs', { cwd: ROOT, stdio: 'inherit' });
}

mkdirSync(path.dirname(RESULTS), { recursive: true });
// A crashed run must not be mistaken for the previous results.
rmSync(RESULTS, { force: true });
try {
  execSync('npx vitest run packages/pack/tests/roundtrip', {
    cwd: ROOT,
    stdio: 'ignore',
    env: { ...process.env, ROUNDTRIP_OUT: RESULTS },
  });
} catch {
  // gaps are expected, results are still dumped
}
if (!existsSync(RESULTS)) {
  console.error('roundtrip: the vitest run did not produce results (compile error?) — run `npx vitest run packages/pack/tests/roundtrip`');
  process.exit(1);
}
const { total, passed, failures } = JSON.parse(readFileSync(RESULTS, 'utf8'));

// group: area/component -> failures
const groups = new Map();
for (const failure of failures) {
  const key = `${failure.area}/${failure.component}`;
  if (!groups.has(key)) groups.set(key, []);
  groups.get(key).push(failure);
}

const countBy = (predicate) => Object.fromEntries(
  CATEGORIES.map((c) => [c, failures.filter((f) => predicate(f) && f.categories.includes(c)).length]),
);
const componentCountBy = (area) => Object.fromEntries(
  CATEGORIES.map((c) => [
    c,
    [...groups].filter(([, list]) => list[0].area === area && list.some((f) => f.categories.includes(c))).length,
  ]),
);

if (process.argv.includes('--update-gaps')) {
  const gaps = {};
  for (const [key, list] of [...groups].sort(([a], [b]) => a.localeCompare(b))) {
    gaps[key] = CATEGORIES.filter((c) => list.some((f) => f.categories.includes(c)));
  }
  writeFileSync(GAPS, `${JSON.stringify(gaps, null, 2)}\n`);
  console.log(`known-gaps.json: ${Object.keys(gaps).length} entries`);
}

const short = (value) => {
  const text = JSON.stringify(value);

  return text === undefined ? '' : text.length > 160 ? `${text.slice(0, 157)}...` : text;
};

const lines = [];
lines.push('# Round-trip report (schema ⊆ SDK)', '');
lines.push(`Generated by \`npm run roundtrip\`. Instances: **${total}**, passed: **${passed}**, failing: **${failures.length}**.`);
lines.push('Sources: vanilla `Mojang/bedrock-samples` corpus + variants generated from the Blockception schemas.');
lines.push('Not covered yet: client entities and animation controllers (no component-level SDK input to compare).', '');
lines.push('## Summary (failing instances / failing components)', '');
lines.push(`| Area | ${CATEGORIES.join(' | ')} |`, `|---|${CATEGORIES.map(() => '---').join('|')}|`);
for (const area of AREAS) {
  const instances = countBy((f) => f.area === area);
  const components = componentCountBy(area);
  lines.push(`| ${area} | ${CATEGORIES.map((c) => `${instances[c]} / ${components[c]}`).join(' | ')} |`);
}
const all = countBy(() => true);
lines.push(`| **total** | ${CATEGORIES.map((c) => `**${all[c]}**`).join(' | ')} |`, '');

for (const area of AREAS) {
  const entries = [...groups].filter(([, list]) => list[0].area === area).sort(([a], [b]) => a.localeCompare(b));
  if (entries.length === 0) continue;
  lines.push(`## ${area}`, '');
  for (const [key, list] of entries) {
    const cats = CATEGORIES.filter((c) => list.some((f) => f.categories.includes(c)));
    lines.push(`### ${key.slice(area.length + 1)} — ${cats.join(', ')} (${list.length})`, '');
    const seen = new Set();
    for (const failure of list) {
      for (const d of failure.details) {
        const id = `${d.category}|${d.path}`;
        if (seen.has(id) || seen.size >= 6) continue;
        seen.add(id);
        const extra = d.message ? ` ${short(d.message)}` : d.expected !== undefined ? ` expected ${short(d.expected)}${d.actual !== undefined ? `, got ${short(d.actual)}` : ''}` : '';
        lines.push(`- \`${d.category}\` \`${d.path}\`${extra}`);
      }
    }
    const repro = list.find((f) => f.source === 'vanilla') ?? list[0];
    lines.push('', `Repro (${repro.source}, \`${repro.origin}\`):`, '', '```json', JSON.stringify({ [repro.component]: repro.json }), '```', '');
  }
}

writeFileSync(REPORT, `${lines.join('\n')}\n`);
writeFileSync(REPORT_JSON, `${JSON.stringify({ total, passed, summary: all, failures }, null, 1)}\n`);
console.log(`roundtrip: ${REPORT} (${failures.length}/${total} failing)`);
console.log(CATEGORIES.map((c) => `${c}=${all[c]}`).join(' '));
