export type DwellerType = 'villager' | 'iron_golem' | 'wandering_trader' | 'pillager' | 'vindicator' | 'evoker' | 'witch' | 'ravager' | 'zombie_villager' | 'zombie' | 'skeleton' | 'creeper' | 'spider' | 'enderman' | 'slime' | 'ghast' | 'blaze' | 'magma_cube' | 'guardian' | 'elder_guardian' | 'shulker' | 'endermite' | 'silverfish' | 'phantom' | 'drowned' | 'husk' | 'stray' | 'wither_skeleton' | 'wither' | 'ender_dragon' | 'player';

export const DWELLER_TYPES: readonly DwellerType[] = [
  'villager',
  'iron_golem',
  'wandering_trader',
  'pillager',
  'vindicator',
  'evoker',
  'witch',
  'ravager',
  'zombie_villager',
  'zombie',
  'skeleton',
  'creeper',
  'spider',
  'enderman',
  'slime',
  'ghast',
  'blaze',
  'magma_cube',
  'guardian',
  'elder_guardian',
  'shulker',
  'endermite',
  'silverfish',
  'phantom',
  'drowned',
  'husk',
  'stray',
  'wither_skeleton',
  'wither',
  'ender_dragon',
  'player'
] as const;
