import {
  ContentDiagnosticContext,
  logContentError,
  logContentWarning,
} from '@ferolyte/common/content/diagnostics/content-diagnostic';
import {
  LANG_KEYS,
  LocalizedString,
  isValidLocalizedString,
} from '@ferolyte/common/content/localization/localized-string';
import type { ComponentOverride } from '../generated/runtime';

const warnIfTexturePath = (
  value: unknown,
  ctx: ContentDiagnosticContext | undefined,
  fieldPath: string,
) => {
  if (typeof value === 'string' && value.startsWith('textures/')) {
    logContentWarning(
      ctx !== undefined ? { ...ctx, fieldPath } : undefined,
      'icon expects an item_texture.json key, not a path',
    );
  }
};

/** SDK sugar of item components; everything else is generated from the schemas. */
export const itemOverrides: Record<string, ComponentOverride> = {
  /** `tags: ['a']` is `{ tags: ['a'] }`. */
  tags: {
    pre: (config) => (Array.isArray(config) ? { tags: config } : config),
  },
  /** `icon: 'key'` is `{ textures: { default: 'key' } }`. */
  icon: {
    pre: (config, ctx) => {
      if (typeof config === 'string') {
        warnIfTexturePath(config, ctx, 'icon');

        return { textures: { default: config } };
      }
      if (typeof config === 'object' && config !== null) {
        for (const [key, value] of Object.entries(config.textures ?? {})) {
          warnIfTexturePath(value, ctx, `textures.${key}`);
        }
      }

      return config;
    },
  },
  /** With a known identifier the value is the language key generated by the compiler. */
  displayName: {
    pre: (config: LocalizedString, ctx) => {
      if (!isValidLocalizedString(config)) {
        logContentError(ctx, 'Display name must be a non-empty string');

        return undefined;
      }

      return {
        value:
          ctx?.identifier !== undefined
            ? LANG_KEYS.item(ctx.identifier)
            : typeof config === 'string'
              ? config
              : Object.values(config)[0],
      };
    },
  },
};
