import {
  convertAdmireItemBehavior,
  convertAvoidBlockBehavior,
  convertAvoidMobTypeBehavior,
  convertBarterBehavior,
  convertBegBehavior,
  convertBreakDoorBehavior,
  convertBreedBehavior,
  convertCelebrateBehavior,
  convertCelebrateSurviveBehavior,
  convertChargeAttackBehavior,
  convertChargeHeldItemBehavior,
  convertCircleAroundAnchorBehavior,
  convertControlledByPlayerBehavior,
  convertCroakBehavior,
  convertDefendTrustedTargetBehavior,
  convertDefendVillageTargetBehavior,
  convertDelayedAttackBehavior,
  convertDigBehavior,
  convertDoorInteractBehavior,
  convertDragonDeathBehavior,
  convertDragonFlamingBehavior,
  convertDragonHoldingPatternBehavior,
  convertDragonLandingBehavior,
  convertDragonScanningBehavior,
  convertDragonStrafePlayerBehavior,
  convertDragonTakeoffBehavior,
  convertDragonChargePlayerBehavior,
  convertDrinkMilkBehavior,
  convertDrinkPotionBehavior,
  convertDropItemForBehavior,
  convertEatBlockBehavior,
  convertEatCarriedItemBehavior,
  convertEatMobBehavior,
  convertEmergeBehavior,
  convertEndermanLeaveBlockBehavior,
  convertEndermanTakeBlockBehavior,
  convertEquipItemBehavior,
  convertExploreOutskirtsBehavior,
  convertFertilizeFarmBlockBehavior,
  convertFindCoverBehavior,
  convertFindMountBehavior,
  convertFindUnderwaterTreasureBehavior,
  convertFireAtTargetBehavior,
  convertFleeSunBehavior,
  convertFloatBehavior,
  convertFloatTemptBehavior,
  convertFloatWanderBehavior,
  convertFollowCaravanBehavior,
  convertFollowMobBehavior,
  convertFollowOwnerBehavior,
  convertFollowParentBehavior,
  convertFollowTargetCaptainBehavior,
  convertFollowTargetLeaderBehavior,
  convertGoAndGiveItemsToNoteblockBehavior,
  convertGoAndGiveItemsToOwnerBehavior,
  convertGoHomeBehavior,
  convertGuardianAttackBehavior,
  convertHarvestFarmBlockBehavior,
  convertHideBehavior,
  convertHoldGroundBehavior,
  convertHurtByTargetBehavior,
  convertInspectBookshelfBehavior,
  convertInvestigateSuspiciousLocationBehavior,
  convertJumpAroundTargetBehavior,
  convertJumpToBlockBehavior,
  convertKnockbackRoarBehavior,
  convertLayDownBehavior,
  convertLayEggBehavior,
  convertLeapAtTargetBehavior,
  convertLookAtEntityBehavior,
  convertLookAtPlayerBehavior,
  convertLookAtTargetBehavior,
  convertLookAtTradingPlayerBehavior,
  convertMakeLoveBehavior,
  convertMeleeAttackBehavior,
  convertMeleeBoxAttackBehavior,
  convertMingleBehavior,
  convertMountPathingBehavior,
  convertMoveAroundTargetBehavior,
  convertMoveIndoorsBehavior,
  convertMoveOutdoorsBehavior,
  convertMoveThroughVillageBehavior,
  convertMoveToBlockBehavior,
  convertMoveToLandBehavior,
  convertMoveToLavaBehavior,
  convertMoveToLiquidBehavior,
  convertMoveToPoiBehavior,
  convertMoveToRandomBlockBehavior,
  convertMoveToVillageBehavior,
  convertMoveToWaterBehavior,
  convertMoveTowardsDwellingRestrictionBehavior,
  convertMoveTowardsHomeRestrictionBehavior,
  convertMoveTowardsRestrictionBehavior,
  convertMoveTowardsTargetBehavior,
  convertNapBehavior,
  convertNearestAttackableTargetBehavior,
  convertNearestPrioritizedAttackableTargetBehavior,
  convertOcelotAttackBehavior,
  convertOcelotSitOnBlockBehavior,
  convertOfferFlowerBehavior,
  convertOpenDoorBehavior,
  convertOwnerHurtByTargetBehavior,
  convertOwnerHurtTargetBehavior,
  convertPanicBehavior,
  convertPetSleepWithOwnerBehavior,
  convertPickupItemsBehavior,
  convertPlaceBlockBehavior,
  convertPlayBehavior,
  convertPlayDeadBehavior,
  convertPlayerRideTamedBehavior,
  convertRaidGardenBehavior,
  convertRamAttackBehavior,
  convertRandomBreachBehavior,
  convertRandomFlyBehavior,
  convertRandomHoverBehavior,
  convertRandomLookAroundAndSitBehavior,
  convertRandomLookAroundBehavior,
  convertRandomSearchAndDigBehavior,
  convertRandomSittingBehavior,
  convertRandomStrollBehavior,
  convertRandomSwimBehavior,
  convertRangedAttackBehavior,
  convertReceiveLoveBehavior,
  convertRestrictOpenDoorBehavior,
  convertRestrictSunBehavior,
  convertRiseToLiquidLevelBehavior,
  convertRoarBehavior,
  convertRollBehavior,
  convertRunAroundLikeCrazyBehavior,
  convertScaredBehavior,
  convertSendEventBehavior,
  convertShareItemsBehavior,
  convertSilverfishMergeWithStoneBehavior,
  convertSilverfishWakeUpFriendsBehavior,
  convertSkeletonHorseTrapBehavior,
  convertSleepBehavior,
  convertSlimeAttackBehavior,
  convertSlimeFloatBehavior,
  convertSlimeKeepOnJumpingBehavior,
  convertSlimeRandomDirectionBehavior,
  convertSnackingBehavior,
  convertSneezeBehavior,
  convertSniffBehavior,
  convertSonicBoomBehavior,
  convertSquidDiveBehavior,
  convertSquidFleeBehavior,
  convertSquidIdleBehavior,
  convertSquidMoveAwayFromGroundBehavior,
  convertSquidOutOfWaterBehavior,
  convertStalkAndPounceOnTargetBehavior,
  convertStayNearNoteBlockBehavior,
  convertStayWhileSittingBehavior,
  convertStompAttackBehavior,
  convertStompTurtleEggBehavior,
  convertStrollTowardsVillageBehavior,
  convertSummonEntityBehavior,
  convertSwellBehavior,
  convertSwimIdleBehavior,
  convertSwimUpForBreathBehavior,
  convertSwimWanderBehavior,
  convertSwimWithEntityBehavior,
  convertSwoopAttackBehavior,
  convertTakeBlockBehavior,
  convertTakeFlowerBehavior,
  convertTargetWhenPushedBehavior,
  convertTeleportToOwnerBehavior,
  convertTemptBehavior,
  convertTimerFlag1Behavior,
  convertTimerFlag2Behavior,
  convertTimerFlag3Behavior,
  convertTradeInterestBehavior,
  convertTradeWithPlayerBehavior,
  convertTransportItemsBehavior,
  convertUseKineticWeaponBehavior,
  convertVexCopyOwnerTargetBehavior,
  convertVexRandomMoveBehavior,
  convertWitherRandomAttackPosGoalBehavior,
  convertWitherTargetHighestDamageBehavior,
  convertWorkBehavior,
  convertWorkComposterBehavior,
} from './behaviors';
import { EntityBehaviors } from '../interfaces/entity-behaviors';
import { ContentDiagnosticContext } from '@artifex/common/content/diagnostics/content-diagnostic';

export type EntityBehaviorConvertor = (
  value?: unknown,
  ctx?: ContentDiagnosticContext,
) => Record<string, unknown> | undefined;

export const entityBehaviorConvertorsFactory: Record<
  keyof EntityBehaviors,
  EntityBehaviorConvertor
> = {
  admireItem: convertAdmireItemBehavior,
  avoidBlock: convertAvoidBlockBehavior,
  avoidMobType: convertAvoidMobTypeBehavior,
  barter: convertBarterBehavior,
  beg: convertBegBehavior,
  breakDoor: convertBreakDoorBehavior,
  breed: convertBreedBehavior,
  celebrate: convertCelebrateBehavior,
  celebrateSurvive: convertCelebrateSurviveBehavior,
  chargeAttack: convertChargeAttackBehavior,
  chargeHeldItem: convertChargeHeldItemBehavior,
  circleAroundAnchor: convertCircleAroundAnchorBehavior,
  controlledByPlayer: convertControlledByPlayerBehavior,
  croak: convertCroakBehavior,
  defendTrustedTarget: convertDefendTrustedTargetBehavior,
  defendVillageTarget: convertDefendVillageTargetBehavior,
  delayedAttack: convertDelayedAttackBehavior,
  dig: convertDigBehavior,
  doorInteract: convertDoorInteractBehavior,
  dragonDeath: convertDragonDeathBehavior,
  dragonFlaming: convertDragonFlamingBehavior,
  dragonHoldingPattern: convertDragonHoldingPatternBehavior,
  dragonLanding: convertDragonLandingBehavior,
  dragonScanning: convertDragonScanningBehavior,
  dragonStrafePlayer: convertDragonStrafePlayerBehavior,
  dragonTakeoff: convertDragonTakeoffBehavior,
  dragonChargePlayer: convertDragonChargePlayerBehavior,
  drinkMilk: convertDrinkMilkBehavior,
  drinkPotion: convertDrinkPotionBehavior,
  dropItemFor: convertDropItemForBehavior,
  eatBlock: convertEatBlockBehavior,
  eatCarriedItem: convertEatCarriedItemBehavior,
  eatMob: convertEatMobBehavior,
  emerge: convertEmergeBehavior,
  endermanLeaveBlock: convertEndermanLeaveBlockBehavior,
  endermanTakeBlock: convertEndermanTakeBlockBehavior,
  equipItem: convertEquipItemBehavior,
  exploreOutskirts: convertExploreOutskirtsBehavior,
  fertilizeFarmBlock: convertFertilizeFarmBlockBehavior,
  findCover: convertFindCoverBehavior,
  findMount: convertFindMountBehavior,
  findUnderwaterTreasure: convertFindUnderwaterTreasureBehavior,
  fireAtTarget: convertFireAtTargetBehavior,
  fleeSun: convertFleeSunBehavior,
  float: convertFloatBehavior,
  floatTempt: convertFloatTemptBehavior,
  floatWander: convertFloatWanderBehavior,
  followCaravan: convertFollowCaravanBehavior,
  followMob: convertFollowMobBehavior,
  followOwner: convertFollowOwnerBehavior,
  followParent: convertFollowParentBehavior,
  followTargetCaptain: convertFollowTargetCaptainBehavior,
  followTargetLeader: convertFollowTargetLeaderBehavior,
  goAndGiveItemsToNoteblock: convertGoAndGiveItemsToNoteblockBehavior,
  goAndGiveItemsToOwner: convertGoAndGiveItemsToOwnerBehavior,
  goHome: convertGoHomeBehavior,
  guardianAttack: convertGuardianAttackBehavior,
  harvestFarmBlock: convertHarvestFarmBlockBehavior,
  hide: convertHideBehavior,
  holdGround: convertHoldGroundBehavior,
  hurtByTarget: convertHurtByTargetBehavior,
  inspectBookshelf: convertInspectBookshelfBehavior,
  investigateSuspiciousLocation: convertInvestigateSuspiciousLocationBehavior,
  jumpAroundTarget: convertJumpAroundTargetBehavior,
  jumpToBlock: convertJumpToBlockBehavior,
  knockbackRoar: convertKnockbackRoarBehavior,
  layDown: convertLayDownBehavior,
  layEgg: convertLayEggBehavior,
  leapAtTarget: convertLeapAtTargetBehavior,
  lookAtEntity: convertLookAtEntityBehavior,
  lookAtPlayer: convertLookAtPlayerBehavior,
  lookAtTarget: convertLookAtTargetBehavior,
  lookAtTradingPlayer: convertLookAtTradingPlayerBehavior,
  makeLove: convertMakeLoveBehavior,
  meleeAttack: convertMeleeAttackBehavior,
  meleeBoxAttack: convertMeleeBoxAttackBehavior,
  mingle: convertMingleBehavior,
  mountPathing: convertMountPathingBehavior,
  moveAroundTarget: convertMoveAroundTargetBehavior,
  moveIndoors: convertMoveIndoorsBehavior,
  moveOutdoors: convertMoveOutdoorsBehavior,
  moveThroughVillage: convertMoveThroughVillageBehavior,
  moveToBlock: convertMoveToBlockBehavior,
  moveToLand: convertMoveToLandBehavior,
  moveToLava: convertMoveToLavaBehavior,
  moveToLiquid: convertMoveToLiquidBehavior,
  moveToPoi: convertMoveToPoiBehavior,
  moveToRandomBlock: convertMoveToRandomBlockBehavior,
  moveToVillage: convertMoveToVillageBehavior,
  moveToWater: convertMoveToWaterBehavior,
  moveTowardsDwellingRestriction: convertMoveTowardsDwellingRestrictionBehavior,
  moveTowardsHomeRestriction: convertMoveTowardsHomeRestrictionBehavior,
  moveTowardsRestriction: convertMoveTowardsRestrictionBehavior,
  moveTowardsTarget: convertMoveTowardsTargetBehavior,
  nap: convertNapBehavior,
  nearestAttackableTarget: convertNearestAttackableTargetBehavior,
  nearestPrioritizedAttackableTarget:
    convertNearestPrioritizedAttackableTargetBehavior,
  ocelotAttack: convertOcelotAttackBehavior,
  ocelotSitOnBlock: convertOcelotSitOnBlockBehavior,
  offerFlower: convertOfferFlowerBehavior,
  openDoor: convertOpenDoorBehavior,
  ownerHurtByTarget: convertOwnerHurtByTargetBehavior,
  ownerHurtTarget: convertOwnerHurtTargetBehavior,
  panic: convertPanicBehavior,
  petSleepWithOwner: convertPetSleepWithOwnerBehavior,
  pickupItems: convertPickupItemsBehavior,
  placeBlock: convertPlaceBlockBehavior,
  play: convertPlayBehavior,
  playDead: convertPlayDeadBehavior,
  playerRideTamed: convertPlayerRideTamedBehavior,
  raidGarden: convertRaidGardenBehavior,
  ramAttack: convertRamAttackBehavior,
  randomBreach: convertRandomBreachBehavior,
  randomFly: convertRandomFlyBehavior,
  randomHover: convertRandomHoverBehavior,
  randomLookAroundAndSit: convertRandomLookAroundAndSitBehavior,
  randomLookAround: convertRandomLookAroundBehavior,
  randomSearchAndDig: convertRandomSearchAndDigBehavior,
  randomSitting: convertRandomSittingBehavior,
  randomStroll: convertRandomStrollBehavior,
  randomSwim: convertRandomSwimBehavior,
  rangedAttack: convertRangedAttackBehavior,
  receiveLove: convertReceiveLoveBehavior,
  restrictOpenDoor: convertRestrictOpenDoorBehavior,
  restrictSun: convertRestrictSunBehavior,
  riseToLiquidLevel: convertRiseToLiquidLevelBehavior,
  roar: convertRoarBehavior,
  roll: convertRollBehavior,
  runAroundLikeCrazy: convertRunAroundLikeCrazyBehavior,
  scared: convertScaredBehavior,
  sendEvent: convertSendEventBehavior,
  shareItems: convertShareItemsBehavior,
  silverfishMergeWithStone: convertSilverfishMergeWithStoneBehavior,
  silverfishWakeUpFriends: convertSilverfishWakeUpFriendsBehavior,
  skeletonHorseTrap: convertSkeletonHorseTrapBehavior,
  sleep: convertSleepBehavior,
  slimeAttack: convertSlimeAttackBehavior,
  slimeFloat: convertSlimeFloatBehavior,
  slimeKeepOnJumping: convertSlimeKeepOnJumpingBehavior,
  slimeRandomDirection: convertSlimeRandomDirectionBehavior,
  snacking: convertSnackingBehavior,
  sneeze: convertSneezeBehavior,
  sniff: convertSniffBehavior,
  sonicBoom: convertSonicBoomBehavior,
  squidDive: convertSquidDiveBehavior,
  squidFlee: convertSquidFleeBehavior,
  squidIdle: convertSquidIdleBehavior,
  squidMoveAwayFromGround: convertSquidMoveAwayFromGroundBehavior,
  squidOutOfWater: convertSquidOutOfWaterBehavior,
  stalkAndPounceOnTarget: convertStalkAndPounceOnTargetBehavior,
  stayNearNoteBlock: convertStayNearNoteBlockBehavior,
  stayWhileSitting: convertStayWhileSittingBehavior,
  stompAttack: convertStompAttackBehavior,
  stompTurtleEgg: convertStompTurtleEggBehavior,
  strollTowardsVillage: convertStrollTowardsVillageBehavior,
  summonEntity: convertSummonEntityBehavior,
  swell: convertSwellBehavior,
  swimIdle: convertSwimIdleBehavior,
  swimUpForBreath: convertSwimUpForBreathBehavior,
  swimWander: convertSwimWanderBehavior,
  swimWithEntity: convertSwimWithEntityBehavior,
  swoopAttack: convertSwoopAttackBehavior,
  takeBlock: convertTakeBlockBehavior,
  takeFlower: convertTakeFlowerBehavior,
  targetWhenPushed: convertTargetWhenPushedBehavior,
  teleportToOwner: convertTeleportToOwnerBehavior,
  tempt: convertTemptBehavior,
  timerFlag1: convertTimerFlag1Behavior,
  timerFlag2: convertTimerFlag2Behavior,
  timerFlag3: convertTimerFlag3Behavior,
  tradeInterest: convertTradeInterestBehavior,
  tradeWithPlayer: convertTradeWithPlayerBehavior,
  transportItems: convertTransportItemsBehavior,
  useKineticWeapon: convertUseKineticWeaponBehavior,
  vexCopyOwnerTarget: convertVexCopyOwnerTargetBehavior,
  vexRandomMove: convertVexRandomMoveBehavior,
  witherRandomAttackPosGoal: convertWitherRandomAttackPosGoalBehavior,
  witherTargetHighestDamage: convertWitherTargetHighestDamageBehavior,
  work: convertWorkBehavior,
  workComposter: convertWorkComposterBehavior,
};

/** @deprecated Use entityBehaviorConvertorsFactory */
export const entityBevaviorConvertorsFactory = entityBehaviorConvertorsFactory;
