// Emits one generated "area" (entity / filters / item / block): types, key maps, validators, registry.
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import Ajv from 'ajv';
import standaloneCode from 'ajv/dist/standalone/index.js';

import {
  buildKeyMap,
  createTypeEmitter,
  pascal,
  snakeToCamel,
  toValidationSchema,
} from './emit.mjs';
import { evidenceFor, loadCorpus } from '../removal-evidence.mjs';
import { stripDocs } from './schema-tree.mjs';

const HEADER =
  '// GENERATED by scripts/schemas/codegen.mjs — do not edit. Run `npm run codegen`.\n';

const IMPORTS = `import type { StateObject } from '../../common/interfaces/state-object';
import type { MolangExpr } from '../../molang/expr/expr';
import type { EntityFilters } from '../../server-entity/interfaces/filters';
import type { PartialEntityEventTrigger } from '../../server-entity/interfaces/trigger';
import type { MinMaxRange } from '../../server-entity/types/min-max-range';
import type { LooseString } from '@ferolyte/common/types/core/loose-string';
`;

const isEmptyObject = (tree) =>
  tree.type === 'object' &&
  Object.keys(tree.properties ?? {}).length === 0 &&
  !tree.additionalProperties &&
  !tree.patternProperties &&
  !tree.oneOf &&
  !tree.anyOf;

/** `boolean | {}` markers also accept a bare boolean. */
const acceptsBoolean = (tree) =>
  (tree.oneOf ?? tree.anyOf ?? []).some((b) => b.type === 'boolean');

/** Marker components: `{}` (or `boolean | {}` in the schema). */
export const isFlag = (tree) => {
  const branches = tree.oneOf ?? tree.anyOf;
  if (Array.isArray(branches)) {
    return (
      branches.every((b) => b.type === 'boolean' || isEmptyObject(b)) &&
      branches.some(isEmptyObject)
    );
  }

  return isEmptyObject(tree);
};

const flagOf = (tree) =>
  isFlag(tree) ? (acceptsBoolean(tree) ? "'boolean'" : 'true') : 'false';

/**
 * @param area {
 *   id: string,
 *   outDir: string,
 *   entries: { key, kind, sdkKey, tree }[],
 *   kinds: Record<kind, { file: string, aggregate: string, suffix: string, registry: string }>,
 *   aggregateKey?: (entry) => string   property name inside the aggregate interface
 * }
 */
/** A component schema without any property that does not say it is a marker (`additionalProperties: false`). */
const isLoose = (tree) =>
  (tree.type === 'object' || tree.type === undefined) &&
  !tree.properties &&
  !tree.oneOf &&
  !tree.anyOf &&
  !tree.allOf &&
  !tree.patternProperties &&
  !tree['x-shared'] &&
  tree.additionalProperties !== false &&
  // A typed map (`additionalProperties: { ...schema }`) is a real schema.
  !(
    typeof tree.additionalProperties === 'object' &&
    Object.keys(tree.additionalProperties).length > 0
  );

/** Fail-closed: every loose schema must be resolved by a patch (real schema, `x-free-form` or `x-removed`). */
export const assertNoUnresolvedLoose = (areaId, entries) => {
  const unresolved = entries.filter(
    (e) => isLoose(e.tree) && !e.tree['x-free-form'] && !e.tree['x-removed'],
  );
  if (unresolved.length > 0) {
    throw new Error(
      [
        `${areaId}: ${unresolved.length} component(s) have a loose schema (no properties). Resolve each in scripts/schemas/patches/`,
        'with a real schema, "x-free-form": "<reason>" or "x-removed": { "since": "…" }:',
        ...unresolved.map((e) => `  ${e.key}`),
      ].join(String.fromCharCode(10)),
    );
  }
};

/**
 * `x-removed` (error + not written) needs proof: an `x-evidence` block, re-checked against the vanilla corpus
 * (`removal-evidence.mjs`) when it is available. Without proof use `x-deprecated` (warning, still written).
 */
export const assertEvidence = (areaId, entries) => {
  const removed = entries.filter((e) => e.tree['x-removed']);
  if (removed.length === 0) return;
  let corpus;
  try {
    corpus = loadCorpus();
  } catch {
    corpus = undefined;
  }
  const problems = [];
  for (const e of removed) {
    const evidence = e.tree['x-evidence'];
    if (!evidence) {
      problems.push(`${e.key}: x-removed without x-evidence (use x-deprecated when there is no proof)`);
      continue;
    }
    if (corpus && evidenceFor(corpus, e.key, evidence.replacements ?? []).since !== e.tree['x-removed'].since) {
      problems.push(`${e.key}: x-removed.since ${e.tree['x-removed'].since} is not what the vanilla corpus proves`);
    }
  }
  if (problems.length > 0) {
    throw new Error([`${areaId}: invalid x-removed`, ...problems.map((p) => `  ${p}`)].join(String.fromCharCode(10)));
  }
};

export const emitArea = (area) => {
  const { id, outDir, entries, kinds } = area;
  assertNoUnresolvedLoose(id, entries);
  assertEvidence(id, entries);
  const typeEmitter = createTypeEmitter();
  const typeName = (entry) =>
    `${pascal(snakeToCamel(entry.sdkKey))}${kinds[entry.kind].suffix}`;
  const aggregateKey = area.aggregateKey ?? ((entry) => entry.sdkKey);
  const quote = (key) => (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key));

  const emitInterfaces = (kind) => {
    let out = '';
    const names = [];
    for (const entry of entries.filter((e) => e.kind === kind)) {
      const name = typeName(entry);
      names.push([aggregateKey(entry), name, entry.key, entry.tree['x-removed'] ?? entry.tree['x-deprecated']]);
      const doc = entry.tree.description ?? entry.tree.title ?? '';
      const removed = entry.tree['x-removed'];
      const replacement = removed?.replacement?.length
        ? ` — use ${removed.replacement.map((r) => `\`${r}\``).join(' / ')}`
        : '';
      const notes = [
        removed
          ? `@deprecated Not in the Bedrock schemas since ${removed.since}${replacement}. Not written when the format version is ${removed.since} or newer.`
          : undefined,
        entry.tree['x-deprecated']
          ? `@deprecated ${entry.tree['x-deprecated'].reason}`
          : undefined,
        entry.tree['x-free-form']
          ? `Free-form component (${entry.tree['x-free-form']}): keys are written as is.`
          : undefined,
      ].filter(Boolean);
      const header = `/**\n * ${[String(doc), ...notes]
        .join('\n')
        .replace(/\*\//g, '*\\/')
        .split(/\r?\n/)
        .join('\n * ')}\n * @minecraft ${entry.key}\n */\n`;
      if (isFlag(entry.tree)) {
        out += acceptsBoolean(entry.tree)
          ? `${header}export type ${name} = StateObject | boolean;\n\n`
          : `${header}export interface ${name} extends StateObject {}\n\n`;
        continue;
      }
      const type = typeEmitter.emit(entry.tree, '');
      const plainObject =
        type.startsWith('{') &&
        !type.includes('} &') &&
        !entry.tree.oneOf &&
        !entry.tree.anyOf &&
        !entry.tree.allOf &&
        !Array.isArray(entry.tree.type);
      out += plainObject
        ? `${header}export interface ${name} ${type}\n\n`
        : `${header}export type ${name} = ${type};\n\n`;
    }

    return { out, names };
  };

  const aggregate = (interfaceName, names) =>
    `export interface ${interfaceName} {\n${names
      .map(
        ([key, name, minecraftKey, removed]) =>
          `  /**${removed ? ` @deprecated ${removed.since ? `Not in the schemas since ${removed.since}.` : removed.reason}` : ''} @minecraft ${minecraftKey} */\n  ${quote(key)}?: ${name};`,
      )
      .join('\n')}\n}\n`;

  const emitted = Object.fromEntries(
    Object.keys(kinds).map((kind) => [kind, emitInterfaces(kind)]),
  );
  const aliasNames = [...typeEmitter.aliases.keys()];
  const aliasImport = aliasNames.length
    ? `import type { ${aliasNames.join(', ')} } from './shared';\n`
    : '';

  mkdirSync(outDir, { recursive: true });
  writeFileSync(
    path.join(outDir, 'shared.ts'),
    `${HEADER}import type { LooseString } from '@ferolyte/common/types/core/loose-string';\n\n${[
      ...typeEmitter.aliases,
    ]
      .map(([n, t]) => `export type ${n} = ${t};\n`)
      .join('\n')}`,
  );
  for (const [kind, spec] of Object.entries(kinds)) {
    writeFileSync(
      path.join(outDir, `${spec.file}.ts`),
      `${HEADER}${IMPORTS}${aliasImport}\n${emitted[kind].out}${aggregate(spec.aggregate, emitted[kind].names)}`,
    );
  }

  writeFileSync(
    path.join(outDir, 'key-maps.ts'),
    `${HEADER}import type { KeyMapNode } from '../key-map';\n\nexport const keyMaps: Record<string, KeyMapNode> = ${JSON.stringify(
      Object.fromEntries(
        entries.map((e) => [`${e.kind}:${e.sdkKey}`, buildKeyMap(e.tree)]),
      ),
      null,
      1,
    )};\n`,
  );

  const ajv = new Ajv({
    strict: false,
    allErrors: true,
    allowUnionTypes: true,
    code: { source: true, esm: true, optimize: true },
  });
  const exportsMap = {};
  for (const entry of entries) {
    const schema = toValidationSchema(stripDocs(entry.tree));
    delete schema.$id;
    const schemaId = `${id}/${entry.kind}/${entry.key}`;
    ajv.addSchema(schema, schemaId);
    exportsMap[`v_${entry.kind}_${entry.sdkKey}`] = schemaId;
  }
  const rawCode = (standaloneCode.default ?? standaloneCode)(ajv, exportsMap);
  // The standalone output `require`s ajv's `equal` helper even in ESM mode: use a local deep-equal instead.
  const UCS2 =
    '(str) => { let len = 0; let pos = 0; const l = str.length; while (pos < l) { len++; const v = str.charCodeAt(pos++); if (v >= 0xd800 && v <= 0xdbff && pos < l) { const w = str.charCodeAt(pos); if ((w & 0xfc00) === 0xdc00) pos++; } } return len; }';
  const code = rawCode
    .replace(
      /const (func\d+) = require\("ajv\/dist\/runtime\/equal"\)\.default;/g,
      'const $1 = (a, b) => JSON.stringify(a) === JSON.stringify(b);',
    )
    .replace(
      /const (func\d+) = require\("ajv\/dist\/runtime\/ucs2length"\)\.default;/g,
      `const $1 = ${UCS2};`,
    );
  if (/require\(/.test(code)) {
    throw new Error(
      `validators.ts still contains require(): ${code.match(/.{0,60}require\([^)]*\).{0,40}/)?.[0]}`,
    );
  }
  writeFileSync(
    path.join(outDir, 'validators.ts'),
    `${HEADER}// @ts-nocheck\n/* eslint-disable */\n${code}`,
  );

  const kindNames = Object.keys(kinds)
    .map((k) => `'${k}'`)
    .join(' | ');
  let registry =
    `${HEADER}import type { GeneratedEntry } from '../key-map';\nimport { keyMaps } from './key-maps';\nimport * as validators from './validators';\n\n` +
    `const entry = (key: string, sdkKey: string, kind: ${kindNames}, flag: boolean | 'boolean', deprecated: boolean | string = false, removed?: { since: string; reason?: string; replacement?: string[] }, freeForm?: string): GeneratedEntry => ({\n  key,\n  sdkKey,\n  kind,\n  flag,\n  deprecated,\n  removed,\n  freeForm,\n  map: keyMaps[kind + ':' + sdkKey],\n  validate: (validators as Record<string, any>)['v_' + kind + '_' + sdkKey],\n});\n\n`;
  for (const [kind, spec] of Object.entries(kinds)) {
    registry += `export const ${spec.registry}: Record<string, GeneratedEntry> = {\n${entries
      .filter((e) => e.kind === kind)
      .map(
        (e) =>
          `  ${quote(aggregateKey(e))}: entry('${e.key}', '${e.sdkKey}', '${kind}', ${flagOf(e.tree)}, ${e.tree['x-deprecated'] ? JSON.stringify(e.tree['x-deprecated'].reason) : e.tree.deprecated ? 'true' : 'false'}, ${JSON.stringify(e.tree['x-removed']) ?? 'undefined'}, ${JSON.stringify(e.tree['x-free-form']) ?? 'undefined'}),`,
      )
      .join('\n')}\n};\n\n`;
  }
  writeFileSync(path.join(outDir, 'registry.ts'), registry);

  return Object.fromEntries(
    Object.entries(emitted).map(([kind, e]) => [kind, e.names.length]),
  );
};
